export enum EOperation {
    PDF_TO_IMAGES,
    PDF_TO_IMAGES_COMPLETE,
    EXTRACT_TEXT_FROM_IMAGE,
    EXTRACT_TEXT_FROM_IMAGE_COMPLETE,
    DELETE_FILES,
    DELETE_FILES_COMPLETE,
    DATABASE_BACKUP,
    DATABASE_BACKUP_COMPLETE,
    DATABASE_RESTORE,
    DATABASE_RESTORE_PROGRESS,
    DATABASE_RESTORE_COMPLETE
};