pipeline {
    agent any
    environment {
        NUXT_API_URL = credentials('NUXT_API_URL')
        NUXT_RECAPTCHA_SITE_KEY = credentials('NUXT_RECAPTCHA_SITE_KEY')
        NUXT_PORT = credentials('NUXT_PORT')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    ls -al
                    node --version
                    npm --version
                    cd frontend-marketing && printf NUXT_API_URL=$NUXT_API_URL\rNUXT_RECAPTCHA_SITE_KEY=$NUXT_RECAPTCHA_SITE_KEY\rNUXT_PORT=$NUXT_PORT > .env && npm ci && npm run build
                    ls -al
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    ls -al
                    cd frontend-marketing && pm2 start ecosystem.config.cjs
                    
                '''
            }
        }
    }
}