pipeline {
    agent any
    environment {
        PORT = credentials('PORT')
        RECAPTCHA_SECRET = credentials('RECAPTCHA_SECRET')
        JWT_SECRET = credentials('JWT_SECRET')
        POSTGRESQL_URL = credentials('POSTGRESQL_URL')
        NODE_ENV = credentials('NODE_ENV')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    ls -al
                    node --version
                    npm --version
                    cd frontend-marketing && printf PORT=$PORT\rRECAPTCHA_SECRET=$RECAPTCHA_SECRET\rJWT_SECRET=$JWT_SECRET\RPOSTGRESQL_URL=$POSTGRESQL_URL\RNODE_ENV=$NODE_ENV > .env && npm ci && npm run start
                    ls -al
                '''
            }
        }
    }
}